#!/usr/bin/env python3
"""
init_tape.py — Quick-generate a VHS .tape file from a template.

Usage:
    python init_tape.py <output.tape> [--tui-command CMD] [--output-format gif|webm|mp4]
                                     [--theme NAME] [--title TEXT] [--minimal]

If no template is specified, generates from the bundled demo template.
The --minimal flag uses the minimal template instead.

Examples:
    python init_tape.py my-demo.tape --tui-command "./myapp" --theme "Dracula"
    python init_tape.py quick.tape --minimal
"""
import argparse
import os
import sys
from pathlib import Path

DEMO_TEMPLATE = """# Generated by init_tape.py
# Usage: vhs {output_filename}

Output {output_file}

Set FontSize 14
Set FontFamily "JetBrains Mono"
Set Width 1000
Set Height 560
Set Padding 16
Set Theme "{theme}"
Set Framerate 60
Set CursorBlink true
Set Shell "bash"
Set LoopOffset 3s

# --- Intro ---
Type@30ms "echo '{title}'"
Enter
Wait+
Sleep 1s

# --- Launch TUI ---
Type@30ms "{tui_command}"
Enter
Sleep 1s

# --- Demo navigation (customize to your TUI's keybindings) ---
Key@1s Down
Key@1s Down
Key@1s Enter
Sleep 2s

Key@500ms Tab
Key@500ms Tab
Sleep 1s

Key@500ms Up
Sleep 1s

# --- Exit ---
Type "q"
Sleep 800ms

# --- Outro ---
Type@30ms "echo 'Demo complete'"
Enter
Sleep 1s
"""

MINIMAL_TEMPLATE = """# Minimal tape — quick test
# Usage: vhs {output_filename}

Output {output_file}

Set FontSize 14
Set Width 600
Set Height 200

Type "echo hello vhs"
Enter
Sleep 1s
"""


def main():
    parser = argparse.ArgumentParser(description="Generate a VHS .tape file")
    parser.add_argument("output", help="Output .tape file path")
    parser.add_argument("--tui-command", default="./your-tui",
                        help="Command to launch the TUI (default: ./your-tui)")
    parser.add_argument("--output-format", choices=["gif", "webm", "mp4"],
                        default="gif", help="Output media format (default: gif)")
    parser.add_argument("--theme", default="Catppuccin Mocha",
                        help="Color theme (default: Catppuccin Mocha)")
    parser.add_argument("--title", default="Welcome to My TUI",
                        help="Intro title text")
    parser.add_argument("--minimal", action="store_true",
                        help="Use minimal template instead of full demo")
    args = parser.parse_args()

    output_path = Path(args.output)
    output_filename = output_path.name
    # Derive media filename from tape filename
    media_filename = output_path.stem + "." + args.output_format

    if args.minimal:
        content = MINIMAL_TEMPLATE.format(
            output_filename=output_filename,
            output_file=media_filename,
        )
    else:
        content = DEMO_TEMPLATE.format(
            output_filename=output_filename,
            output_file=media_filename,
            theme=args.theme,
            title=args.title,
            tui_command=args.tui_command,
        )

    output_path.write_text(content, encoding="utf-8")
    print(f"Generated: {output_path}")
    print(f"Output media will be: {media_filename}")
    print(f"Run: vhs {output_filename}")


if __name__ == "__main__":
    main()
