-- Generated by scripts/build-task-share.mjs.
-- Seeds the official catalog into D1; live user interactions update counters after deploy.

INSERT INTO tasks (name, title, description, author_name, download_count, like_count, favorite_count, created_at)
VALUES
	('bili-up-homepage-spider', 'Bili Up Homepage Spider', '给定B站UP主主页视频标签链接和页码，获取该页码下所有视频的标题、链接和发布时间，并保存为JSON文件', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('bilibili-downloader', 'Bilibili Downloader', '下载B站视频 https://www.bilibili.com/video/BV18ejU6wEKn/ 到本地指定文件夹，使用yt-dlp并从Chrome获取cookies获取最高画质', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('linkedin-search', 'Linkedin Search', '给定 keyword 和时间意图,dispatcher 把时间归并到 LinkedIn 原生三档(past-24h/past-week/past-month),worker 用 UGK 管理的 chrome_cdp 搜索 LinkedIn 内容(按最新排序 + 时间档位过滤),把完整结构化结果写入 $TASK_OUTPUT_DIR/linkedin_search_results.json。headless 友好,并行安全。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('subtitle-fluent-translator', 'Subtitle Fluent Translator', '给定一个本地源字幕文件,产出经过阅读理解、翻译和断句优化后的流畅中文字幕 SRT。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('subtitle-to-speech', 'Subtitle To Speech', '给定一个中文字幕文件,用 MiMo TTS 生成按字幕时间轴铺好的中文配音音频。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('video-downloader', 'Video Downloader', '给定一个公开视频 URL,用 yt-dlp 下载其中的单个视频为 MP4,并在存在字幕时下载字幕文件。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('video-zh-composer', 'Video Zh Composer', '给定视频、中文配音音频和中文字幕,产出中文配音软字幕版 MP4 与硬字幕版 MP4。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('video-zh-dubber', 'Video Zh Dubber', '给定本地视频文件和英文字幕文件,一体化产出中文字幕、中文配音音轨,以及带中文字幕软字幕和硬字幕的最终 MP4。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('whisper-audio-to-text', 'Whisper Audio To Text', '给定本地音视频文件,使用本机 Whisper large-v3-turbo 转写,产出可继续用于字幕优化和配音流程的 SRT/VTT/TXT/JSON。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('x-search', 'X Search', '给定 keyword 和自然语言时间意图,dispatcher 把时间算成扁平标量字段(startIso/endIso 等),worker 用 UGK 管理的 chrome_cdp 搜索 X/Twitter Latest,按 [startIso,endIso) 过滤,把完整结构化结果写入 $TASK_OUTPUT_DIR/x_search_results.json。headless 友好,并行安全。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z'),
	('x-video-downloader', 'X Video Downloader', '给定 X/Twitter 帖子链接,下载其中的视频为 MP4,并在存在字幕时下载字幕文件。', 'UGK Official', 0, 0, 0, '2026-06-30T00:00:00.000Z')
ON CONFLICT(name) DO UPDATE SET
	title = excluded.title,
	description = excluded.description,
	author_name = excluded.author_name;
